// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuXRMlPGtLn1h9FJ2meCgxFDxYBeX34Bs',
    appId: '1:90878816990:web:872c8041bad3baa631084f',
    messagingSenderId: '90878816990',
    projectId: 'flutter-app-20448',
    authDomain: 'flutter-app-20448.firebaseapp.com',
    storageBucket: 'flutter-app-20448.firebasestorage.app',
    measurementId: 'G-LFF6EM6P16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIjBlkfVHoMxAB3y1fK0XAH-swnxY6cvY',
    appId: '1:90878816990:android:c33d82b8d0154a1731084f',
    messagingSenderId: '90878816990',
    projectId: 'flutter-app-20448',
    storageBucket: 'flutter-app-20448.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYkrBLEFaf0sS6lf79h0dADU7uU7S2l3s',
    appId: '1:90878816990:ios:704d7fc91148f47b31084f',
    messagingSenderId: '90878816990',
    projectId: 'flutter-app-20448',
    storageBucket: 'flutter-app-20448.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYkrBLEFaf0sS6lf79h0dADU7uU7S2l3s',
    appId: '1:90878816990:ios:704d7fc91148f47b31084f',
    messagingSenderId: '90878816990',
    projectId: 'flutter-app-20448',
    storageBucket: 'flutter-app-20448.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuXRMlPGtLn1h9FJ2meCgxFDxYBeX34Bs',
    appId: '1:90878816990:web:dd27923c8c17d12f31084f',
    messagingSenderId: '90878816990',
    projectId: 'flutter-app-20448',
    authDomain: 'flutter-app-20448.firebaseapp.com',
    storageBucket: 'flutter-app-20448.firebasestorage.app',
    measurementId: 'G-BQQEVTZG1F',
  );
}
